### ISSUE TITLE
CSS animations

### ISSUE THREAD

**Issue by ghost** [mdmoreau/flextabs#1]
Can someone point me in the direction of how to add animation when clicking on the accordion tabs?
The transition is abrupt at the moment.  I would like to smooth it out with a delay and a small bit of bounce.

**Comment by mdmoreau** [comment]
The easiest way would be to use a combination of `max-height: 0` and `overflow: hidden` on `.flextabs__content` and then use an extra container inside of that for the content itself.  You can then set `max-height` on the active states to animate.

It's not a perfect solution by any means, but I haven't gotten around to setting up better animation calculations.  Check out a quick example I made over at http://codepen.io/mdmoreau/pen/xgGaQX.  The main changes are done at the bottom of the CSS tab.
