### ISSUE TITLE
Previous and Next Buttons

### ISSUE THREAD

**Issue by dmfnft** [mdmoreau/flextabs#2]
How to have a previous and a next buttons to navigate between tabs ? thx

**Comment by mdmoreau** [comment]
@dmfnft If the goal is to switch between tabs and have one active at a time, you should be able to handle that by toggling the `flextabs__toggle--active--last` and `flextabs__content--active--last` classes on the items when a button is clicked. You could query one of those classes, find the closest sibling item (previous or next), add the classes to the nodes there, and then remove them from the other nodes.

I don't think it's something I'd add into the core script, but it should be simple enough to work out with a little logic. Let me know if that helps.
